set -e fish_greeting

alias develop='cd ~/Documents/develop'
alias gofish='cd ~/.config/fish'
alias govim='cd ~/.vim'
alias gonginx='cd /usr/local/etc/nginx'
alias gocars='cd ~/Documents/develop/cars'
alias g='git'
alias gst='git status'
alias gd='git diff'
alias gl='git pull'
alias gup='git pull --rebase'
alias gp='git push'
alias gcmsg='git commit -am'
alias gcmsn='git commit -n -m'
alias gb='git branch'
alias grbi='git rebase -i'
alias grbc='git rebase --continue'
alias grba='git rebase --abort'
alias grbs='git rebase --skip'
alias ga='git add'
alias gaa='git add --all'
alias gsta='git stash'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gstd='git stash drop'
alias gco='git checkout'
alias gcm='git checkout master'
